name: SCYS Spider ServerChan

on:
  schedule:
      - cron: '0 1 * * *'
          - cron: '0 10 * * *'
            workflow_dispatch:

            jobs:
              spider:
                  runs-on: ubuntu-latest
                      steps:
                          - name: Checkout code
                                uses: actions/checkout@v3
                                    - name: Setup Python
                                          uses: actions/setup-python@v4
                                                with:
                                                        python-version: '3.9'
                                                            - name: Install dependencies
                                                                  run: |
                                                                          python -m pip install --upgrade pip
                                                                                  pip install -r requirements.txt
                                                                                      - name: Run spider
                                                                                            env:
                                                                                                    SERVER_CHAN_KEY: ${{ secrets.SERVER_CHAN_KEY }}
                                                                                                          run: |
                                                                                                                  echo "Starting SCYS spider..."
                                                                                                                          python spider.py
                                                                                                                              - name: Upload logs
                                                                                                                                    if: always()
                                                                                                                                          uses: actions/upload-artifact@v3
                                                                                                                                                with:
                                                                                                                                                        name: spider-logs-${{ github.run_number }}
                                                                                                                                                                path: |
                                                                                                                                                                          *.log
                                                                                                                                                                                    sent_posts.db
                                                                                                                                                                                            retention-days: 7
